name: Deploy via ftp
      on: push
      jobs:
        deploy:
          name: Deploy
          runs-on: ubuntu-latest
          steps:
          - uses: actions/checkout@v2

          - name: FTP Deploy Locaweb
            uses: locaweb/ftp-deploy@1.0.0
            with:
              host: ftp.senexcare.com.br
              user: senexcare1
              password: ${{ secrets.SENEXCARE }}
              localDir: ./ #
